### ISSUE TITLE
Changes to Scratch support for extensions!

### ISSUE THREAD

**Issue by wizzwizz4** [jbaragry/mcpi-scratch#1]
Not all of the following text will display. :disappointed:
This has hit everybody hard; but either you need to tell people to use http://scratchx.org/ or you need to follow this (temporary) workaround I discovered as part of the Scratch Experimental JavaScript Extension Developer's group:
Create a gh-pages branch of mcpi-scratch, and put the JavaScript file in it. This will create a GitHub pages site, with the file hosted on it (located at jbaragry.github.io/mcpi-scratch/file.js). Then, create a bookmarklet which creates a <script> tag in the DOM with the src element of "//jbaragry.git...ch/file.js". Then, create a new project and, if it is to be shared, share it first. Then, click on the bookmarklet. Now the blocks are loaded!
This will ALWAYS work on scratchx.org, however, not forever on scratch.mit.edu.
I suggest you change readme.md.

**Comment by jbaragry** [comment]
thanks. I've started looking into a fix

**Comment by wizzwizz4** [comment]
Ok. By the way... http://llk.github.io/scratch-extension-docs has some (almost enough) info on this.

**Comment by jbaragry** [comment]
I think I've got it fixed now. I still need to create the github page, but you can test already if you like. Just download a new version of the python helper app and use the following url with scratchx
https://rawgit.com/jbaragry/mcpi-scratch/master/mcpi-scratch.js

**Comment by wizzwizz4** [comment]
I think the js file has to be on the gh-pages... but I haven't tried rawgit!

**Comment by jbaragry** [comment]
No, that's just a convention. You can use any url. 
This link works: http://scratchx.org/?url=https://rawgit.com/jbaragry/mcpi-scratch/master/mcpi-scratch.js
